name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: golang-enthusiast/app-yaml-env-compiler@v1.0
        env:
          PG_USER: ppp
          PG_PASSWORD: qqq
          PG_DATABASE: qqq
          PG_TEST_DATABASE: qqq
          API_SECRET: qqq
    
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.3'
        with:
           credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.5.0
