name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: golang-enthusiast/app-yaml-env-compiler@v1.0
        env:
          PG_USER: '${{ secrets.PG_USER }}'
          PG_PASSWORD: '${{ secrets.PG_PASSWORD }}'
          PG_DATABASE: '${{ secrets.PG_DATABASE }}'
          PG_TEST_DATABASE: '${{ secrets.PG_TEST_DATABASE }}'
          PG_HOST: '${{ secrets.PG_HOST }}'
          API_SECRET: '${{ secrets.API_SECRET }}'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.3'
        with:
           credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.5.0
