name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
           create_credentials_file: 'true'
           workload_identity_provider: 'projects/3561524957/locations/global/workloadIdentityPools/github-pool-id/providers/github'
           service_account: 'go-learn-96427@appspot.gserviceaccount.com'
           project_id: 'go-learn-96427'
           
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
            gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
            gcloud services list

      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
