name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
           workload_identity_provider: 'projects/3561524957/locations/global/workloadIdentityPools/github-pool-id/providers/github'
           service_account: 'go-learn-96427@appspot.gserviceaccount.com'

      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
