name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          project_id : $ {{env.PROJECT_ID}} 
          service_account_key : $ {{secrets.GCP_SA_KEY}}

      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
