name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials: ${{ secrets.gcp_credentials }}

      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
