name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
    
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.3'
        with:
           token_format: 'access_token'
           workload_identity_provider: 'projects/3561524957/locations/global/workloadIdentityPools/github-pool-id/providers/github'
           service_account: 'go-learn-96427@appspot.gserviceaccount.com'
           project_id: 'go-learn-96427'
           
      - id: 'access-secret'
        run: |-
          curl https://secretmanager.googleapis.com/v1/projects/3561524957/secrets/github-secret/versions/1:access \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
      
      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.5.0
        with:
          deliverables: app.yaml
